name: AutoClicker
options:
  bundleIdPrefix: com.autoclicker
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO

targets:
  AutoClicker:
    type: application
    platform: macOS
    sources:
      - path: Sources/AutoClicker
        type: group
      - path: Resources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.autoclicker.AutoClicker
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_NAME: AutoClicker
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_ENTITLEMENTS: Resources/AutoClicker.entitlements
